alias ll='ls -la'
alias gc='git commit -m'
alias ga='git add'
alias gaa='git add .'
alias gs='git status'
alias gl='git log'
alias glg='git log --oneline --graph'
alias gb='git branch'
alias gbd='git branch -D'
alias gpu='git push'
alias gpl='git pull'
alias gch='git checkout'
alias gcb='git checkout -b'
alias gdsf='git dsf'
alias gff='git flow feature'
alias gffs='git flow feature start'
alias gfff='git flow feature finish'
alias gffpu='git flow feature publish'
alias gffp='git flow feature pull'
alias gfr='git flow release'
alias gfrs='git flow release start'
alias gfrf='git flow release finish'
alias gfrp='git flow release publish'
alias vup='vagrant up'
alias vh='vagrant halt'
alias unzip6='/usr/local/Cellar/unzip/6.0/bin/unzip'
alias art='php artisan'
alias test='vendor/bin/phpunit'

# Git branch in prompt.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] $ "
